// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQY-tXbLL-u1MLGDo_keO2HmSnmaAOlF0',
    appId: '1:1017620600279:web:1ef89648b5c2d17f56e792',
    messagingSenderId: '1017620600279',
    projectId: 'memorizewholetext',
    authDomain: 'memorizewholetext.firebaseapp.com',
    storageBucket: 'memorizewholetext.appspot.com',
    measurementId: 'G-HYV1GDPW35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSS9ux9P1sEKK7oOR8c7RiAguE5-rsCLk',
    appId: '1:1017620600279:android:d50ad5dc0f98795a56e792',
    messagingSenderId: '1017620600279',
    projectId: 'memorizewholetext',
    storageBucket: 'memorizewholetext.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-xzyjFMGe7MWPWkaCT-lkloXTgFtIjk',
    appId: '1:1017620600279:ios:235221522bcb0bc756e792',
    messagingSenderId: '1017620600279',
    projectId: 'memorizewholetext',
    storageBucket: 'memorizewholetext.appspot.com',
    iosBundleId: 'com.example.funEnglishWithDad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN-xzyjFMGe7MWPWkaCT-lkloXTgFtIjk',
    appId: '1:1017620600279:ios:235221522bcb0bc756e792',
    messagingSenderId: '1017620600279',
    projectId: 'memorizewholetext',
    storageBucket: 'memorizewholetext.appspot.com',
    iosBundleId: 'com.example.funEnglishWithDad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQY-tXbLL-u1MLGDo_keO2HmSnmaAOlF0',
    appId: '1:1017620600279:web:cffd6df027c3a7b256e792',
    messagingSenderId: '1017620600279',
    projectId: 'memorizewholetext',
    authDomain: 'memorizewholetext.firebaseapp.com',
    storageBucket: 'memorizewholetext.appspot.com',
    measurementId: 'G-J1HE246NWS',
  );
}
